# To boot the app run the following:
# docker-compose run auto-gpt

version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    volumes:
      - "./scripts:/app"
      - "env-volume:/app/.env"
      - "logs:/app/logs"
    # profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"
    volumes:
      - "redis_data:/data"

volumes:
  redis_data:
  env-volume:
  logs:
